services:
  postgresql:
    container_name: postgresql
    image: postgres:15.4-bullseye
    restart: always

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432" # para crear otra instancia cambiar 5436 pero dejar igual 5432

    volumes:
      # es buena practica path relativo desde el proyecto ./_data:/var/lib/postgresql
      - ./_data:/var/lib/postgresql/data
    networks:
      - mired

  pg-admin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:8
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - ./_pgadmin_data:/var/lib/pgadmin
    networks:
      - mired
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - ./_mongo_data:/data/db

networks:
  mired:
    external: true
#volumes:
 # mongo_data: